name = "NSDELinearMultistep"
uuid = "6991faac-6e0a-407a-9214-ea0dabeacbe6"
authors = ["Giancarlo A. Antonucci"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
